build:
	g++ src/App.cpp src/VertexBuffer.cpp src/IndexBuffer.cpp -o bin -lglad -lglfw3 -framework Cocoa -framework OpenGL -framework IOKit -framework CoreFoundation -framework CoreVideo

run:build
	./bin